//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace DailyQuest {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class DailyQuestConfig : ApplicationSettingsBase {
        
        private static DailyQuestConfig defaultInstance = ((DailyQuestConfig)(Synchronized(new DailyQuestConfig())));
        
        public static DailyQuestConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AutoRequest {
            get {
                return ((bool)(this["AutoRequest"]));
            }
            set {
                this["AutoRequest"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool BagNotifications {
            get {
                return ((bool)(this["BagNotifications"]));
            }
            set {
                this["BagNotifications"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool AutoTurnIn {
            get {
                return ((bool)(this["AutoTurnIn"]));
            }
            set {
                this["AutoTurnIn"] = value;
            }
        }
    }
}
