//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class GlowSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlowSettings defaultInstance = ((GlowSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlowSettings())));
        
        public static GlowSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GlowEnable {
            get {
                return ((bool)(this["GlowEnable"]));
            }
            set {
                this["GlowEnable"] = value;
            }
        }
    }
}
