//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Specialized;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace ChatAssist {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class ChatAssistConfig : ApplicationSettingsBase {
        
        private static ChatAssistConfig defaultInstance = ((ChatAssistConfig)(Synchronized(new ChatAssistConfig())));
        
        public static ChatAssistConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool Enabled {
            get {
                return ((bool)(this["Enabled"]));
            }
            set {
                this["Enabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AutoIgnoreSpamPM {
            get {
                return ((bool)(this["AutoIgnoreSpamPM"]));
            }
            set {
                this["AutoIgnoreSpamPM"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AutoIgnoreSpamMessage {
            get {
                return ((bool)(this["AutoIgnoreSpamMessage"]));
            }
            set {
                this["AutoIgnoreSpamMessage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CensorSpamMessages {
            get {
                return ((bool)(this["CensorSpamMessages"]));
            }
            set {
                this["CensorSpamMessages"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DisableMessages {
            get {
                return ((bool)(this["DisableMessages"]));
            }
            set {
                this["DisableMessages"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool EnableNPCFilter {
            get {
                return ((bool)(this["EnableNPCFilter"]));
            }
            set {
                this["EnableNPCFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool EnableSpamFilter {
            get {
                return ((bool)(this["EnableSpamFilter"]));
            }
            set {
                this["EnableSpamFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int StarFilter {
            get {
                return ((int)(this["StarFilter"]));
            }
            set {
                this["StarFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int StarFilterPM {
            get {
                return ((int)(this["StarFilterPM"]));
            }
            set {
                this["StarFilterPM"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool LogChat {
            get {
                return ((bool)(this["LogChat"]));
            }
            set {
                this["LogChat"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool AutoResponse {
            get {
                return ((bool)(this["AutoResponse"]));
            }
            set {
                this["AutoResponse"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>LIFEPOT. ORG</string>
  <string>RealmStock</string>
  <string>ORYX.lN</string>
  <string>RealmPower</string>
  <string>RealmItems</string>
  <string>Rea!mKings</string>
  <string>Realm$aver</string>
</ArrayOfString>")]
        public StringCollection Blacklist {
            get {
                return ((StringCollection)(this["Blacklist"]));
            }
            set {
                this["Blacklist"] = value;
            }
        }
    }
}
