//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace LootHelper {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class LootHelperConfig : ApplicationSettingsBase {
        
        private static LootHelperConfig defaultInstance = ((LootHelperConfig)(Synchronized(new LootHelperConfig())));
        
        public static LootHelperConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool LootNotifications {
            get {
                return ((bool)(this["LootNotifications"]));
            }
            set {
                this["LootNotifications"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool AutoLoot {
            get {
                return ((bool)(this["AutoLoot"]));
            }
            set {
                this["AutoLoot"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Health Potion, Magic Potion, Potion of Life, Potion of Mana, Potion of Dexterity," +
            " Potion of Vitality, Potion of Defense, Potion of Speed, Potion of Wisdom, Potio" +
            "n of Attack")]
        public string AutoLootList {
            get {
                return ((string)(this["AutoLootList"]));
            }
            set {
                this["AutoLootList"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool LootQuests {
            get {
                return ((bool)(this["LootQuests"]));
            }
            set {
                this["LootQuests"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Aqua")]
        public Color NotificationColor {
            get {
                return ((Color)(this["NotificationColor"]));
            }
            set {
                this["NotificationColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal, Purple, Egg, Blue, Cyan, White, Red")]
        public string LootBags {
            get {
                return ((string)(this["LootBags"]));
            }
            set {
                this["LootBags"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Blue, Cyan, White, Red")]
        public string NotifBags {
            get {
                return ((string)(this["NotifBags"]));
            }
            set {
                this["NotifBags"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public byte AutoLootWeaponTier {
            get {
                return ((byte)(this["AutoLootWeaponTier"]));
            }
            set {
                this["AutoLootWeaponTier"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public byte AutoLootArmorTier {
            get {
                return ((byte)(this["AutoLootArmorTier"]));
            }
            set {
                this["AutoLootArmorTier"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public byte AutoLootAbilityTier {
            get {
                return ((byte)(this["AutoLootAbilityTier"]));
            }
            set {
                this["AutoLootAbilityTier"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public byte AutoLootRingTier {
            get {
                return ((byte)(this["AutoLootRingTier"]));
            }
            set {
                this["AutoLootRingTier"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public byte AutoLootEggTier {
            get {
                return ((byte)(this["AutoLootEggTier"]));
            }
            set {
                this["AutoLootEggTier"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Blue, Cyan, White")]
        public string QuestBags {
            get {
                return ((string)(this["QuestBags"]));
            }
            set {
                this["QuestBags"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("700")]
        public int LootSpeed {
            get {
                return ((int)(this["LootSpeed"]));
            }
            set {
                this["LootSpeed"] = value;
            }
        }
    }
}
