//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Specialized;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace MapFilter {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MapFilterConfig : ApplicationSettingsBase {
        
        private static MapFilterConfig defaultInstance = ((MapFilterConfig)(Synchronized(new MapFilterConfig())));
        
        public static MapFilterConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool Enabled {
            get {
                return ((bool)(this["Enabled"]));
            }
            set {
                this["Enabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Blue Sprite Tree=&gt;None</string>
  <string>White Sprite Tree=&gt;None</string>
  <string>Green Sprite Tree=&gt;None</string>
  <string>Red Sprite Tree=&gt;None</string>
  <string>Purple Sprite Tree=&gt;None</string>
  <string>Yellow Sprite Tree=&gt;None</string>
</ArrayOfString>")]
        public StringCollection ObjectFilters {
            get {
                return ((StringCollection)(this["ObjectFilters"]));
            }
            set {
                this["ObjectFilters"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ice Slide=&gt;Gold Tile</string>\r\n</ArrayOfString>")]
        public StringCollection TileFilters {
            get {
                return ((StringCollection)(this["TileFilters"]));
            }
            set {
                this["TileFilters"] = value;
            }
        }
    }
}
