//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Sprite {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Config : ApplicationSettingsBase {
        
        private static Config defaultInstance = ((Config)(Synchronized(new Config())));
        
        public static Config Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SpriteTrees {
            get {
                return ((bool)(this["SpriteTrees"]));
            }
            set {
                this["SpriteTrees"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool SpriteSpace {
            get {
                return ((bool)(this["SpriteSpace"]));
            }
            set {
                this["SpriteSpace"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SpriteFloor {
            get {
                return ((bool)(this["SpriteFloor"]));
            }
            set {
                this["SpriteFloor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IceSlide {
            get {
                return ((bool)(this["IceSlide"]));
            }
            set {
                this["IceSlide"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PanicMode {
            get {
                return ((bool)(this["PanicMode"]));
            }
            set {
                this["PanicMode"] = value;
            }
        }
    }
}
